name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Defina a branch que dispara o workflow de build

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build JAR
        run: ./mvnw package  # Comando para construir o JAR do Spring Boot
      
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Build Docker image
        run: docker build -t aners/sistema-teatro:latest .
      
      - name: Push Docker image to Docker Hub
        run: docker push aners/sistema-teatro:latest
